exclude:
  - 'assets/src/styles/_bootstrap-import.scss'

linters:
  ColorVariable:
    enabled: false
  ImportantRule:
    enabled: false
  LeadingZero:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  UnnecessaryMantissa:
    enabled: false
  UrlFormat:
    enabled: false
