
# Site settings
title: 'Jekyll Bootstrap Starter'
email: ackernaut@gmail.com
description: 'Jekyll Bootstrap Starter'
baseurl:          /jekyll-bootstrap-starter
url:              http://ackernaut.github.io
name:             'Jekyll Bootstrap Starter'
permalink:        pretty
twitter_username: ackernaut
github_username:  ackernaut
port: 4040

# Build settings
markdown: kramdown
exclude:  [node_modules]
